### ISSUE TITLE
Nonsymmetric SDP matrix

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/CDCS#13]
How does CDCS interpret a nonsymmetric SDP matrix ? For instance, if in the dual form,
A'y gives the matrix
```
[1 x
 y 1]
```
what does it do ? Does it interpret it as
```
[1 (x+y)/2
 (x+y)/2 1]
```
should be PSD (like SeDuMi does)
or that
```
[1 x
 x 1]
```
should be PSD and `y` should be equal to `x`

**Comment by giofantuzzi** [comment]
Hi @blegat,

CDCS works like SeDuMi: the constraint
```
[1 x
 y 1] >= 0
```
is interpreted as
```
[1 (x+y)/2
 (x+y)/2 1] >= 0
```

More precisely, for all available sub-solvers ([+cdcs_hsde](https://github.com/oxfordcontrol/CDCS/tree/master/packages/%2Bcdcs_hsde), [+cdcs_pd](https://github.com/oxfordcontrol/CDCS/tree/master/packages/%2Bcdcs_pd) and [+cdcs_sos](https://github.com/oxfordcontrol/CDCS/tree/master/packages/%2Bcdcs_sos)), the input data is pre-processed by [svecData.m](https://github.com/oxfordcontrol/CDCS/blob/master/packages/%2Bcdcs_utils/svecData.m). This routine symmetrizes any vectorized PSD matrix `A'y`, and at the same time transforms it to the "economical" form based on symmetric vectorization.

Hope this helps, let us know if you have any further queries.

**Comment by blegat** [comment]
Thank you for the answer!
