### ISSUE TITLE
Error if K.q is empty 

### ISSUE THREAD

**Issue by martinandersen** [oxfordcontrol/CDCS#6]
I get the following error message if `K.q = []`:

```
Operands to the || and && operators must be convertible to logical scalar
values.

Error in cdcs_utils.checkInputs (line 40)
if (isfield(K,'q') && max(K.q) > 0)

Error in cdcs (line 104)
[At,b,c,K,opts] = checkInputs(At,b,c,K,opts);
``` 
Of course I can get around that issue by deleting the field `q` from `K` before calling `cdcs`.
However, it may be more user friendly to check that `K.q` is nonempty in `checkInputs`:

```
isfield(K,'q') && ~isempty(K.q) && max(K.q) > 0
```

**Comment by zhengy09** [comment]
Hi Martin,

Many thanks for pointing out this bug. We also noticed this before, and we have corrected it in the 'sos-problem' branch. We will release a new version soon.

Please do let us know if you find any other issues.

Best,
Yang
